# Generated by Django 3.2.9 on 2021-11-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nome', models.CharField(max_length=15)),
                ('sobre_nome', models.CharField(max_length=20)),
                ('dt_nasc', models.DateField()),
                ('cpf', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMININO')], max_length=1)),
                ('dt_cadastro', models.DateTimeField(auto_now_add=True)),
                ('dt_alteracao', models.DateTimeField()),
                ('sn_ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
