# Generated by Django 3.2.9 on 2021-11-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dt_alteracao',
            field=models.DateTimeField(null=True),
        ),
    ]
