# Generated by Django 3.2.9 on 2021-11-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_dt_alteracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
